# Header
menu:
  Home: /
  Archives: /archives
  Resume: /2016/01/26/简历/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: zhuqling
google_plus:
fb_admins:
fb_app_id: